INFURA_PUBLIC_KEY = ''
INFURA_PASSPHRASE = ''
INFURA_SECRET_KEY = ''


NODE_PROVIDER = ''
CONTRACT_ADDRESS = ''
CONTRACT_ABI = ''

GANACHE_NODE_PROVIDER = ''
ADDRESS_1 = ''
GANACHE_SECRET_KEY_ADDRESS_1 = ''
ADDRESS_2 = ''
GANACHE_SECRET_KEY_ADDRESS_2 = ''


